---
title: "rides_analysis"
author: "Michael Spencer"
date: "7/11/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SETUP
```{r}
library(tidyverse)
library(sf)
```

## PARAMS

Retrieve Uber data from fivethirtyeight github
```{r}
uber_raw_data_april14_url <- "https://github.com/fivethirtyeight/uber-tlc-foil-response/raw/master/uber-trip-data/uber-raw-data-apr14.csv"

uber_raw_data_may14_url <-
"https://github.com/fivethirtyeight/uber-tlc-foil-response/raw/master/uber-trip-data/uber-raw-data-may14.csv"
```

## LOAD DATA

Load in and combine the uber pickups for April and May of 2014
```{r}
uber_trip_april_data <- read_csv(file = uber_raw_data_april14_url, progress = TRUE)

uber_trip_may_data <- read_csv(file = uber_raw_data_may14_url, progress = TRUE)
```

```{r}
uber_trip_data <- rbind(uber_trip_april_data, uber_trip_may_data)
```

## PLOT DATA

Note: Decreasing size further does not affect appearence, though decreasing alpha can create a heatmap of sort and enhance "resolution". Increasing the size of the output jpeg's drastically improves the appearence of the map.
```{r}
prepped_uber_trip_data <-
  uber_trip_data %>% 
  st_as_sf(coords = c("Lon", "Lat"), crs = 4326) %>%
  st_transform(crs = 102003) %>% 
  st_coordinates() %>% 
  as.data.frame()

#Gives metro area views at high resolution
##Uncomment line below to save high resolution image
#jpeg("nyc_metro_1M.jpeg", units = "in", width = 75, height = 50, res = 300)
prepped_uber_trip_data %>% 
  ggplot() +
  geom_point(aes(X, Y), size = 1e-12, color = "#83a48b") +
  coord_cartesian(xlim = c(1800000, 1850000), ylim = c(560000, 590000)) +
  theme_void() +
  theme(panel.background = element_rect(fill = "black"))
##Uncoment line below to save high resolution image
#dev.off()

#Gives Manhattan View
##Uncomment line below to save high resolution image
#jpeg("manh_1M.jpeg", units = "in", width = 75, height = 50, res = 300)
prepped_uber_trip_data %>% 
  ggplot() +
  geom_point(aes(X, Y), size = 1e-8, color = "#83a48b") +
  coord_cartesian(xlim = c(1820000, 1840000), ylim = c(570000, 585000)) +
  theme_void() +
  theme(panel.background = element_rect(fill = "black"))
##Uncoment line below to save high resolution image
#dev.off()
```

